/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package e01

import org.apache.commons.io.FileUtils
import java.nio.file.*
import java.io.File
import com.google.gson.*


fun readFile(path: String, format: String, callback: (String) -> Unit) {
    Thread() {
        var content = FileUtils.readFileToString(File(path), format)
        callback(content)
    }.start()
}

fun main(args: Array<String>) {
        println("A")
        if(args.size > 0) {
            readFile(args[0], "utf-8") {
                var jsonObject : JsonObject = JsonParser().parse(it).getAsJsonObject()
                var name = jsonObject.get("name").getAsString()
                var height = jsonObject.get("height").getAsString().toInt()
                var mass = jsonObject.get("mass").getAsString().toInt()
                var bmi = mass.toDouble() / (height.toDouble() * height) * 10000
                val f = "%.2f".format(bmi)
                println("BMI of $name is $f")
            }
        }
        println("B")
}

