/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e01

import kotlin.test.Test
import kotlin.test.*

class AppTest {
    @Test fun testIsPalindrome() {
        assertTrue("saippuakauppias".isPalindrome(), "should return true")
        assertFalse("abc".isPalindrome(), "should return false")

        assertTrue("SaippuakauPPias".isPalindrome(ignoreCase = true), "should return true")
        assertFalse("SaippuakauPPias".isPalindrome(), "should return true")

        assertTrue("Saippua kauPPias".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = true), "should return true")
        assertFalse("Saippua kauPPias".isPalindrome(ignoreCase = true), "should return false")
        assertFalse("Saippua kauPPias".isPalindrome(ignoreWhiteSpaces = true), "should return false")
        assertFalse("Saippua kauPPias".isPalindrome(), "should return false")
    }
}
