/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

package e01

import org.apache.commons.io.FileUtils
import java.nio.file.*
import java.io.File


fun readFile(path: String, format: String, callback: (String) -> Unit) {
    Thread() {
        var content = FileUtils.readFileToString(File(path), format)
        callback(content)
    }.start()
}

fun main(args: Array<String>) {
        println("A")
        if(args.size > 0) {
            readFile(args[0], "utf-8") {
                println(it)
            }
        }
        println("B")
}

