/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package e01

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun String.isPalindrome(ignoreCase: Boolean = false, ignoreWhiteSpaces: Boolean = false) : Boolean {
    var str = this
    if(ignoreCase) str = str.toLowerCase()
    if(ignoreWhiteSpaces) str = str.replace("\\s".toRegex(), "")

    var tempWord = ""
    for(i in str.length - 1 downTo 0) {
        tempWord += str[i]
    }
    if(str == tempWord) return true else return false
}

fun main() {
   println("saippuakauppias".isPalindrome()) // true
   println("abc".isPalindrome()) // false
   println("SaippuakauPPias".isPalindrome(ignoreCase = true)) // true
   println("Saippua kauPPias".isPalindrome(ignoreCase = true, ignoreWhiteSpaces = true)) // true
}
